everhealth_product_reporting:
  outputs:

    dev:
      type: postgres
      threads: 1  # Set the number of threads according to your requirements
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number}}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dev_schema  # Update this with your actual schema for development

    prod:
      type: postgres
      threads: 1  # Set the number of threads according to your requirements
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      user: prod_username  # Replace with your production username
      pass: prod_password  # Replace with your production password
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: prod_schema  # Update this with your actual schema for production

  target: dev